// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kfkzjrabvwxzmmwbxkwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtma3pqcmFidnd4em1td2J4a3dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTUyMjAsImV4cCI6MjA2MzA3MTIyMH0.rz0BhV35e6lBpwnl3uyol8j8CLyPEaRxq1xuBpMkmsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);